bookstore/books/urls.py
from django.conf.urls import url
from books import views

urlpatterns = [
    url(r'^$', views.index, name='index'), # 首页
    url(r'books/(?P<books_id>\d+)/$', views.detail, name='detail'), # 详情页
]

bookstore/bookstore/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/',include('users.urls',namespace='user')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'',include('books.urls',namespace='books')),#商品模块
]

bookstore/users/urls.py
from django.conf.urls import url 
from users import views


urlpatterns = [
    url(r'^register/$',views.register, name='register'), # 用户注册
    url(r'^register_handle/$', views.register_handle, name='register_handle'), # 用户注册处理
    url(r'^login/$',views.login,name = 'login'),#显示登录页
    url(r'^login_check/$', views.login_check, name='login_check'), # 用户登录校验
    url(r'^logout/$', views.logout, name='logout'), # 退出用户登录
]

bookstore/books/models.py
from django.db import models
from db.base_model import BaseModel
from books.enums import *
# Create your models here.
class BooksManager(models.Manager):
    def get_books_by_type(self,type_id,limit= None,sort= 'default'):
        if sort == 'new':
            order_by = ('-create_time',)
        elif sort == 'hot':
            order_by = ('-sales',)
        elif sort == 'price':
            order_by = ('price',)
        else:
            order_by = ('-pk')

        books_li = self.filter(type_id= type_id).order_by(*order_by)

        if limit:
            books_li = books_li[:limit]
        return books_li


    def get_books_by_id(self,books_id):
        try:
            books = self.get(id=books_id)

        except self.models.DoseNotExit():
            books = None
        return books



class Books(BaseModel):
    
    books_type_choices =((k,v) for k,v in BOOKS_TYPE.items())
    
    status_choices = ((k, v) for k,v in STATUS_CHOICE.items())

    type_id = models.SmallIntegerField(default=PYTHON,choices=books_type_choices,verbose_name='商品种类')
    
    name = models.CharField(max_length=20,verbose_name='商品名称')

    desc = models.CharField(max_length=128,verbose_name='商品简介')

    price = models.DecimalField(max_digits=10,decimal_places=2,verbose_name='商品价格')

    unit = models.CharField(max_length=20,verbose_name='商品单位')

    stock = models.IntegerField(default=1,verbose_name='商品库存')

    sales = models.IntegerField(default=0,verbose_name='商品销量')

    detail = models.SmallIntegerField(verbose_name='商品详情')
    
    image = models.ImageField(upload_to= 'books',verbose_name='商品图片')
    
    status = models.SmallIntegerField(default=ONLINE,choices=status_choices,verbose_name='商品状态')


    objects = BooksManager()

    # admin显示书籍的名字
    def __str__(self):
        return self.name

    class Meta:
        db_table = 's_books'
        verbose_name = '书籍'
        verbose_name_plural = '书籍'

bookstore/users/models.py
from django.db import models
from utils.get_hash import get_hash
from db.base_model import BaseModel
# Create your models here.

class PassportManager(models.Manager):
    def add_one_passport(self,username,password,email):
        #t添加一个账户信息
        passport = self.create(username=username,password=get_hash(password,email = email))

        return passport
    
    def get_one_passport(self,username,passworld):
        try:
            passport = self.get(username=username,passworld=Get_hash(passworld))

        except self.model.DoseNotExit:
            passport = None
        return passport



class Passport(BaseModel):
    username = models.CharField(max_length=20,unique=True,verbose_name='用户昵称')
    password = models.CharField(max_length=40,verbose_name= '用户密码')
    email = models.EmailField(verbose_name= '用户邮箱')
    is_actve= models.BooleanField(default=False,verbose_name='激活状态')

    #用户表的管理器
    objects = PassportManager()

    class Meta:
        db_table = 's_user_account'

bookstore/books/views.py
from django.shortcuts import render
from books.models import Books
from books.enums import *
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator
# Create your views here.


def index(request):
    '''显示首页'''
    # 查询每个种类的3个新品信息和4个销量最好的商品信息
    python_new = Books.objects.get_books_by_type(PYTHON, limit=3, sort='new')
    python_hot = Books.objects.get_books_by_type(PYTHON, limit=4, sort='hot')
    javascript_new = Books.objects.get_books_by_type(JAVASCRIPT,limit= 3, sort='new')
    javascript_hot = Books.objects.get_books_by_type(JAVASCRIPT, limit=4, sort='hot')
    algorithms_new = Books.objects.get_books_by_type(ALGORITHMS, 3, sort='new')
    algorithms_hot = Books.objects.get_books_by_type(ALGORITHMS, 4, sort='hot')
    machinelearning_new = Books.objects.get_books_by_type(MACHINELEARNING, 3, sort='new')
    machinelearning_hot = Books.objects.get_books_by_type(MACHINELEARNING, 4, sort='hot')
    operatingsystem_new = Books.objects.get_books_by_type(OPERATINGSYSTEM, 3, sort='new')
    operatingsystem_hot = Books.objects.get_books_by_type(OPERATINGSYSTEM, 4, sort='hot')
    database_new = Books.objects.get_books_by_type(DATABASE, 3, sort='new')
    database_hot = Books.objects.get_books_by_type(DATABASE, 4, sort='hot')

    # 定义模板上下文
    context = {
        'python_new': python_new,
        'python_hot': python_hot,
        'javascript_new': javascript_new,
        'javascript_hot': javascript_hot,
        'algorithms_new': algorithms_new,
        'algorithms_hot': algorithms_hot,
        'machinelearning_new': machinelearning_new,
        'machinelearning_hot': machinelearning_hot,
        'operatingsystem_new': operatingsystem_new,
        'operatingsystem_hot': operatingsystem_hot,
        'database_new': database_new,
        'database_hot': database_hot,
    }
    # 使用模板
    return render(request, 'books/index.html', context)


def detail(request,book_id):
    books = Books.objects.get_books_by_id(books_id= books_id)

    if books is None:
        return redirect(reverse('books:index'))
    
    book_li = Books.objects.get_books_by_type(type_id= books.type_id,limit=2,sort='new')

    type_title = BOOKS_TYPE[books.type_id]
    
    context = {'books':books,'books_li':books_li,'type_title':type_title }

    return render(request,'books/detail.html',context)

bookstore/users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
import re 
from users.models import Passport

# Create your views here.

def register(request):
    return render(request,'users/register.html')


def register_handle(request):
    
    username = request.POST.get('user_name')

    password = request.POST.get('pwd')
    
    email = request.POST.get('email')

    if not all([username,password,email]):
        return render(request,'user/register.html',{'errmsg':'参数不能为空' })

    try:
        passport.object.add_one_passport(username=username, password=password, email=email)
    except:
        return render(request, 'users/register.html', {'errmsg': '用户名已存在！'})

    # 注册完，还是返回注册页。
    return redirect(reverse('user:register'))

def login(request):
    if request.COOKIES.get('username'):
        username = request.COOKIES.get('username')
        checked = 'checked'

    else:
        username = ''

        checked = ''
    context = {
        'username':username,
        'checked':checked,
        }

    return render(request,'users/login.html',context)



def login_check(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    remeber = request.POST.get('remeber')

    if not all([username,password,remeber]):
        return JsonResponse({'res':2})
    
    password = Passport.object.get_one_passport(username = username,password=password)

    if passport:
        next_url = reverse('books:index')
        jres = JsonResponse({'res':1,'next_url':next_url})

        #判断是否需要记住用户名
        if remeber == 'true':
            jres.set_cookie('username',username,max_length=7*24*3600)

        else:
            jres.delete_cookie('username')

        request.session['islogin']=True
        request.session['username']=username
        request.session['passport_id']=passport_id
        return jres
    else:
        return JsonResponse({'res':0})

   

def logout(request):
    request.session.flush()
    return redirect(reverse('books:index'))

bookstore/templates/base.html
{# 首页 登录 注册 的父模板 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页顶部标题块 #}
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bulma.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
    {# 网页顶部引入文件块 #}
	{% block topfiles %}
	{% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到尚硅谷书店!</div>
			<div class="fr">
                {% if request.session.islogin %}
				<div class="login_btn fl">
					欢迎您：<em>{{ request.session.username }}</em>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'order:place' %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
{% endblock header_con %}
{# 网页顶部搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'books:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}" style="width: 160px; height: 53px;"></a>
		<div class="search_con fl">
            <form method="get" action="/search/">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
			<div class="book_count fl" id="show_count">0</div>
		</div>
	</div>
{% endblock search_bar %}
{# 网页主体内容块 #}
{% block body %}{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京尚硅谷信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {# 获取用户购物车中商品的数目 #}
    {% block cart_count %}
        <script>
            $.get('/cart/count/', function (data) {
                // {'res':商品的总数}
                $('#show_count').html(data.res)
            })
        </script>
    {% endblock cart_count %}
    {# 网页底部html元素块 #}
    {% block bottom %}{% endblock bottom %}
    {# 网页底部引入文件块 #}
	{% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

bookstore/templates/books/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书店-首页{% endblock title %}
{% block topfiles %}
<script>
$(function () {
    update_total_price()
    // 计算总价
    function update_total_price() {
        // 获取商品的价格和数量
        books_price = $('.show_pirze').children('em').text()
        books_count = $('.num_show').val()
        // 计算商品的总价
        books_price = parseFloat(books_price)
        books_count = parseInt(books_count)
        total_price = books_price * books_count
        // 设置商品总价
        $('.total').children('em').text(total_price.toFixed(2) + '元')
    }

    // 商品增加
    $('.add').click(function () {
        // 获取商品的数量
        books_count = $('.num_show').val()
        // 加1
        books_count = parseInt(books_count) + 1
        // 重新设置值
        $('.num_show').val(books_count)
        // 计算总价
        update_total_price()
    })

    // 商品减少
    $('.minus').click(function () {
        // 获取商品的数量
        books_count = $('.num_show').val()
        // 加1
        books_count = parseInt(books_count) - 1
        if (books_count == 0){
            books_count = 1
        }
        // 重新设置值
        $('.num_show').val(books_count)
        // 计算总价
        update_total_price()
    })

    // 手动输入
    $('.num_show').blur(function () {
        // 获取商品的数量
        books_count = $(this).val()
        // 数据校验
        if (isNaN(books_count) || books_count.trim().length == 0 || parseInt(books_count) <= 0 ){
            books_count = 1
        }
        // 重新设置值
        $('.num_show').val(parseInt(books_count))
        // 计算总价
        update_total_price()
    })
})
</script>
{% endblock topfiles %}
{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="#" class="python">Python</a></li>
					<li><a href="#" class="javascript">Javascript</a></li>
					<li><a href="#" class="algorithms">数据结构与算法</a></li>
					<li><a href="#" class="machinelearning">机器学习</a></li>
					<li><a href="#" class="operatingsystem">操作系统</a></li>
					<li><a href="#" class="database">数据库</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">移动端书城</a></li>
				<li class="interval">|</li>
				<li><a href="">秒杀</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">Python</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="book_detail_con clearfix">
		<div class="book_detail_pic fl"><img src="{% static books.image %}"></div>

		<div class="book_detail_list fr">
			<h3>{{ books.name }}</h3>
			<p>{{ books.desc }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ books.price }}</em></span>
				<span class="show_unit">单  位：{{ books.unit }}</span>
			</div>
			<div class="book_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>	
				</div> 
			</div>
			<div class="total">总价：<em>100元</em></div>
			<div class="operate_btn">
                {% csrf_token %}
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" books_id="{{ books.id }}" class="add_cart" id="add_cart">加入购物车</a>
				<a href="#" id="write-comment" class="comment">我要写评论</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_book">
				<h3>新品推荐</h3>
				<ul>
                    {% for book in books_li %}
					<li>
						<a href="{% url 'books:detail' books_id=books.id %}"><img src="{% static book.image %}"></a>
						<h4><a href="{% url 'books:detail' books_id=books.id %}">{{ book.name }}</a></h4>
						<div class="prize">￥{{ book.price }}</div>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active" id="detail">商品介绍</li>
				<li id="comment">评论</li>
			</ul>

			<div class="tab_content">
				<dl id="book_detail">
					<dt>商品详情：</dt>
					<dd>{{ books.detail | safe }}</dd>
				</dl>
				<dl id="book_comment">
				</dl>
			</div>

		</div>
	</div>
	<div class="add_jump"></div>
{% endblock body %}
{% block bottomfiles %}
<script type="text/javascript">
	$('#add_cart').click(function(){
        // 获取商品的id和商品数量
        var books_id = $(this).attr('books_id');
        var books_count = $('.num_show').val();
        var csrf = $('input[name="csrfmiddlewaretoken"]').val();
        // 发起请求，访问/cart/add/, 进行购物车数据的添加
        var params = {
        	'books_id': books_id, 
        	'books_count': books_count,
            'csrfmiddlewaretoken': csrf
        }

        $.post('/cart/add/', params, function (data) {
            if (data.res == 5){
                // 添加成功
				var count = $('#show_count').html();
				var count = parseInt(count) + parseInt(books_count);
				$('#show_count').html(count);
            }
            else {
                // 添加失败
                alert(data.errmsg);
            }
        })
	})

	$('#write-comment').click(function() {
		window.open("{% url 'comment:comment' book_id=books.id %}")
	})
</script>
    <style type="text/css">
        .comment {
            background-color: #c40000;
            color: #fff;
            margin-left: 10px;
            position: relative;
            z-index: 10;
            display: inline-block;
            width: 178px;
            height: 38px;
            border: 1px solid #c40000;
            font-size: 14px;
            line-height: 38px;
            text-align: center;
        }
    </style>
{% endblock bottomfiles %}

bookstore/templates/books/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书店-首页{% endblock title %}
{% block topfiles %}
{% endblock topfiles %}
{% block body %}

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">移动端书城</a></li>
				<li class="interval">|</li>
				<li><a href="">秒杀</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="python">Python</a></li>
			<li><a href="#model02" class="javascript">Javascript</a></li>
			<li><a href="#model03" class="algorithms">数据结构与算法</a></li>
			<li><a href="#model04" class="machinelearning">机器学习</a></li>
			<li><a href="#model05" class="operatingsystem">操作系统</a></li>
			<li><a href="#model06" class="database">数据库</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="{% static 'images/slide.jpg' %}" alt="幻灯片" style="width: 760px; height: 270px;"></li>
				<li><img src="{% static 'images/slide02.jpg' %}" alt="幻灯片" style="width: 760px; height: 270px;"></li>
				<li><img src="{% static 'images/slide03.jpg' %}" alt="幻灯片" style="width: 760px; height: 270px;"></li>
				<li><img src="{% static 'images/slide04.jpg' %}" alt="幻灯片" style="width: 760px; height: 270px;"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="{% static 'images/adv01.jpg' %}" style="width: 240px; height: 135px;"></a>
			<a href="#"><img src="{% static 'images/adv02.jpg' %}" style="width: 240px; height: 135px;"></a>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">Python</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for book in python_new %}
				    <a href="{% url 'books:detail' books_id=book.id %}">{{ book.name }}</a>
                {% endfor %}
			</div>
			<a href="{% url 'books:list' type_id=1 page=1 %}" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="{% static 'images/banner01.jpg' %}"></div>
			<ul class="book_list fl">
                {% for book in python_hot %}
				<li>
					<h4><a href="{% url 'books:detail' books_id=book.id  %}">{{ book.name }}</a></h4>
					<a href="{% url 'books:detail' books_id=book.id  %}"><img src="{% static book.image %}"></a>
					<div class="prize">¥ {{ book.price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model02">Javascript</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for book in javascript_new %}
				    <a href="#">{{ book.name }}</a>
                {% endfor %}
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="{% static 'images/banner02.jpg' %}"></div>
			<ul class="book_list fl">
                {% for book in javascript_hot %}
				<li>
					<h4><a href="#">{{ book.name }}</a></h4>
					<a href="#"><img src="{% static book.image %}"></a>
					<div class="prize">¥ {{ book.price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model03">数据结构与算法</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for book in algorithms_new %}
				    <a href="#">{{ book.name }}</a>
                {% endfor %}
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="{% static 'images/banner03.jpg' %}"></div>
			<ul class="book_list fl">
                {% for book in algorithms_hot %}
				<li>
					<h4><a href="#">{{ book.name }}</a></h4>
					<a href="#"><img src="{% static book.image %}"></a>
					<div class="prize">¥ {{ book.price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model04">机器学习</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for book in machinelearning_new %}
				    <a href="#">{{ book.name }}</a>
                {% endfor %}
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="{% static 'images/banner04.jpg' %}"></div>
			<ul class="book_list fl">
                {% for book in machinelearning_hot %}
				<li>
					<h4><a href="#">{{ book.name }}</a></h4>
					<a href="#"><img src="{% static book.image %}"></a>
					<div class="prize">¥ {{ book.price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model05">操作系统</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for book in operatingsystem_new %}
				    <a href="#">{{ book.name }}</a>
                {% endfor %}
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="{% static 'images/banner05.jpg' %}"></div>
			<ul class="book_list fl">
                {% for book in operatingsystem_hot %}
				<li>
					<h4><a href="#">{{ book.name }}</a></h4>
					<a href="#"><img src="{% static book.image %}"></a>
					<div class="prize">¥ {{ book.price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model06">数据库</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for book in database_new %}
				    <a href="#">{{ book.name }}</a>
                {% endfor %}
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="{% static 'images/banner06.jpg' %}"></div>
			<ul class="book_list fl">
                {% for book in database_hot %}
				<li>
					<h4><a href="#">{{ book.name }}</a></h4>
					<a href="#"><img src="{% static book.image %}"></a>
					<div class="prize">¥ {{ book.price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>

{% endblock body %}

bookstore/templates/users/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书城-登录{% endblock title %}
{% block topfiles %}
<script>
    $(function () {
        $('#btnLogin').click(function () {
            // 获取用户名和密码
            username = $('#username').val()
            password = $('#pwd').val()
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            remember = $('input[name="remember"]').prop('checked')
            vc = $('input[name="vc"]').val()
            // 发起ajax请求
            params = {
            	'username': username,
            	'password': password,
                'csrfmiddlewaretoken': csrf,
                'remember': remember,
                'verifycode': vc,
            }
            console.log('params: ', params)
            $.post('/user/login_check/', params, function (data) {
                // 用户名密码错误 {'res':0}
                // 登录成功 {'res':1}
                console.log('data: ', data)
                if (data.res == 0){
                    $('#username').next().html('用户名或密码错误').show()
                }
                else
                {
                    // 跳转页面
                    location.href = data.next_url // /user/
                }
            })
        })
    })
</script>
{% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
<body>
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="{% static 'images/logo.png' %}" style="width: 160px; height: 53px;"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">学计算机 · 来尚硅谷</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="#">立即注册</a>
				</div>
				<div class="form_input">
                    {% csrf_token %}
					<input type="text" id="username" class="name_input" value="{{ username }}" placeholder="请输入用户名">
					<div class="user_error">输入错误</div>
					<input type="password" id="pwd" class="pass_input" placeholder="请输入密码">
					<div class="pwd_error">输入错误</div>
					<div style="top: 100px; position: absolute;">
						<input type="text" id="vc" name="vc">
						<img id='verifycode' src="/user/verifycode/" alt="CheckCode"/>
					</div>
					<div class="more_input clearfix">
						<input type="checkbox" name="remember" {{ checked }}>
						<label>记住用户名</label>
						<a href="#">忘记密码</a>
					</div>
					<input type="button" id="btnLogin" value="登录" class="input_submit">
				</div>
			</div>
		</div>
	</div>
{% endblock body %}
{% block cart_count %}{% endblock cart_count %}